### ISSUE TITLE
Minor text corrections on Reference page

### ISSUE THREAD

**Issue by rupeshkumar22** [codeanticode/processing-android-website#24]
Transferring this from 
https://github.com/processing/processing-android/issues/752

@codeanticode @ranaaditya
Let me know if we require an update of the website and its tutorials, 
You may share your ideas if we require website redesigning and logo replacement to the latest one, 
I will share some quick samples based on your views to go ahead. Although can't appreciate enough the knowledge the website provides, Can we try to enhance the look and feel of the website along with tutorial updates? Thanks!

**Comment by ranaaditya** [comment]
> Transferring this from [processing/processing-android#752](https://github.com/processing/processing-android/issues/752)
> 
> @codeanticode @ranaaditya Let me know if we require an update of the website and its tutorials, You may share your ideas if we require website redesigning and logo replacement to the latest one, I will share some quick samples based on your views to go ahead. Although can't appreciate enough the knowledge the website provides, Can we try to enhance the look and feel of the website along with tutorial updates? Thanks!

Hi @rupeshkumar22 yes definetly we need new and more interactive examples on the website, also we need to update the websote content as well.

For this if you want we can start a new github discussion as well to have better and at a place communication.

Thanks,
Aditya Rana

**Comment by ranaaditya** [comment]
Hi @rupeshkumar22 , you can open a PR for the changes that you like to add to the website, i would love to review the PR.

Thanks,
rana !

**Comment by rupeshkumar22** [comment]
Hi @ranaaditya 
I will open a PR soon with some initial changes, I am starting with the current issues lined up on the repo, and later on, we may plan on what will go next. I'm planning to cover all the upcoming changes to a single PR, would that be fine for us?
Thanks,
Rupesh

**Comment by SableRaf** [comment]
Hi @rupeshkumar22 and thanks again for your contribution. I know it's been quite a while but should you wish to pick up where you left off, feel free to create a new issue on specific design or content updates you would like to work on. cc @ranaaditya
