### ISSUE TITLE
A tiny bug in the sample code

### ISSUE THREAD

**Issue by WinDerek** [codeanticode/processing-android-website#5]
I went through the following page and found a tiny bug in the sample code.
[http://android.processing.org/tutorials/getting_started/index.html](http://android.processing.org/tutorials/getting_started/index.html)
![tiny_bug](https://cloud.githubusercontent.com/assets/15662234/23784287/06bc9b58-059c-11e7-8c0a-39749a08f441.png)
I have reviewed the index.html file and found the corresponding bug in **line 81**.
Obviously, `&lt;` should be `<`, which is caused by the wrong code `&amp;lt;` in the file index.html.
Although it might not be worth mentioning, I think it's confusing for those beginners who want to learn processing for Android.
In fact, I've learned about Processing before and I'm interested in Processing for Android. I'm a sophomore at the School of Software Engineering in Tongji University, Shanghai. I really want to contribute to Processing for Android. I have decent experience in Android developing and have developed some Android applications, some of which can be found on [my Github](https://github.com/derekdick). Where should I start contributing?
@codeanticode

**Comment by codeanticode** [comment]
@DerekDick Many thanks for the fix! I have already updated the site.

As for further contributions, feel free to look at the [open issues](https://github.com/processing/processing-android/issues) in the processing-android repo and see if there is anything you would like to work on. I will be more than happy to provide any guidance you might need.

Also, you should consider applying to [GSoC 2017](https://developers.google.com/open-source/gsoc/), in which the Processing Fundation is a participating organization. We have a number of high-priority projects that GSoC students could pick up (look for the items under the Processing for Android section in the [project list wiki](https://github.com/processing/processing/wiki/Project-List)). There is also an [ongoing discussion](https://forum.processing.org/two/categories/summer-of-code-2017) on the Processing forum about ideas for GSoC.
